/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    solutions: Solution;
    articles: Article;
    news: News;
    leadership: Leadership;
    facilities: Facility;
    'board-members': BoardMember;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-metrics': SiteMetric;
  };
  globalsSelect: {
    'site-metrics': SiteMetricsSelect<false> | SiteMetricsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * URL path segment — lowercase, hyphens only
   */
  slug: string;
  domain: 'EV' | 'ADAS' | 'Powertrain' | 'Thermal' | 'Chassis' | 'Connected' | 'Interiors';
  /**
   * CMS publishing state — not the product lifecycle stage, see Lifecycle status below
   */
  status?: ('draft' | 'published') | null;
  /**
   * Product lifecycle stage (was legacy lifecycle status)
   */
  lifecycleStatus?: ('active-production' | 'beta-validation' | 'engineering-sample' | 'end-of-life') | null;
  /**
   * e.g. "Battery Thermal Modules" — from legacy CMS data partFamily
   */
  partFamily?: string | null;
  vehicleSegments?: ('passenger-cars' | 'commercial-vehicles' | 'off-highway' | 'motorcycles-powersports')[] | null;
  certifications?:
    | ('IATF 16949' | 'ISO 9001:2015' | 'ISO 14001' | 'ISO 26262 ASIL D' | 'ISO 26262 ASIL B' | 'REACH' | 'RoHS')[]
    | null;
  /**
   * e.g. "GM", "Ford"
   */
  oemCompatibility?: string[] | null;
  technicalDataSheetUrl?: string | null;
  featuredOnHomepage?: boolean | null;
  /**
   * One-paragraph teaser shown on the solutions listing page
   */
  summary: string;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specs?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Used by screen readers and search engines
   */
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  publishedAt: string;
  status?: ('draft' | 'published') | null;
  /**
   * Product domain this article relates to — separate from Topic category below
   */
  domain?: ('EV' | 'ADAS' | 'Powertrain' | 'Thermal' | 'Chassis' | 'Connected') | null;
  /**
   * Innovation topic (legacy category) — a different classification than Domain above
   */
  topicCategory?:
    | (
        | 'software-defined-vehicle'
        | 'electrification'
        | 'hydrogen-fuel-cell'
        | 'cybersecurity'
        | 'ee-architecture'
        | 'autonomous-driving'
        | 'circular-economy'
      )
    | null;
  authorName?: string | null;
  authorRole?: string | null;
  readTimeMinutes?: number | null;
  isWhitePaper?: boolean | null;
  whitePaperAsset?: (number | null) | Media;
  featuredOnHomepage?: boolean | null;
  /**
   * One-paragraph summary shown on listing and social share
   */
  excerpt: string;
  coverImage: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Link to related product solutions
   */
  relatedSolutions?: (number | Solution)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  publishedAt: string;
  status?: ('draft' | 'published') | null;
  /**
   * What kind of item this is — separate from Topic category below, which is what it's about. Optional field; legacy records may not have a value.
   */
  type?: ('press-release' | 'award' | 'partnership' | 'product-update' | 'event') | null;
  /**
   * Subject area (legacy category) — also what the newsroom sidebar counts should group by
   */
  topicCategory?: ('technical' | 'corporate' | 'esg' | 'financial' | 'partnerships') | null;
  /**
   * Source / byline attribution
   */
  attribution?: string | null;
  readTimeMinutes?: number | null;
  featuredMaterial?: boolean | null;
  excerpt: string;
  /**
   * Leave empty and set External URL if this item links out to a third-party article
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If set, "Read more" links to this URL instead of an internal article page
   */
  externalUrl?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  jobTitle: string;
  department?: ('executive' | 'engineering' | 'operations' | 'commercial' | 'finance' | 'hr') | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait: number | Media;
  linkedin?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  name: string;
  location: string;
  country: string;
  countryCode?: string | null;
  /**
   * What kind of site this is — distinct from Status below, which is its build phase
   */
  facilityType?: ('manufacturing' | 'rd-centre' | 'sales-office') | null;
  status?: ('operational' | 'construction' | 'planned') | null;
  floorAreaM2?: number | null;
  headcount?: number | null;
  /**
   * Bucketed range as reported historically, e.g. "500-1000" — kept separate from the exact Headcount figure above
   */
  employeeRange?: string | null;
  /**
   * Plain yes/no flag — not inferred from the Certifications list below
   */
  iatfCertified?: boolean | null;
  certifications?:
    | {
        name: string;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw capability tags as originally recorded — see Specialties below for the structured equivalent
   */
  capabilities?: string[] | null;
  specialties?: ('battery' | 'machining' | 'thermal' | 'adas' | 'software' | 'moulding')[] | null;
  heroImage?: (number | null) | Media;
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  title: string;
  /**
   * e.g. "Audit Committee (Chair)" — optional
   */
  committee?: string | null;
  type: 'executive' | 'independent' | 'non-executive';
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  department?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  domain?: T;
  status?: T;
  lifecycleStatus?: T;
  partFamily?: T;
  vehicleSegments?: T;
  certifications?: T;
  oemCompatibility?: T;
  technicalDataSheetUrl?: T;
  featuredOnHomepage?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  status?: T;
  domain?: T;
  topicCategory?: T;
  authorName?: T;
  authorRole?: T;
  readTimeMinutes?: T;
  isWhitePaper?: T;
  whitePaperAsset?: T;
  featuredOnHomepage?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  relatedSolutions?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  status?: T;
  type?: T;
  topicCategory?: T;
  attribution?: T;
  readTimeMinutes?: T;
  featuredMaterial?: T;
  excerpt?: T;
  body?: T;
  externalUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  jobTitle?: T;
  department?: T;
  bio?: T;
  portrait?: T;
  linkedin?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  country?: T;
  countryCode?: T;
  facilityType?: T;
  status?: T;
  floorAreaM2?: T;
  headcount?: T;
  employeeRange?: T;
  iatfCertified?: T;
  certifications?:
    | T
    | {
        name?: T;
        year?: T;
        id?: T;
      };
  capabilities?: T;
  specialties?: T;
  heroImage?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  committee?: T;
  type?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-metrics".
 */
export interface SiteMetric {
  id: number;
  /**
   * Display string, e.g. "$1.2B"
   */
  revenueRunRate: string;
  revenueYear: string;
  facilityCount: number;
  headcount: number;
  iatfCertifiedCount: number;
  countryCount: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-metrics_select".
 */
export interface SiteMetricsSelect<T extends boolean = true> {
  revenueRunRate?: T;
  revenueYear?: T;
  facilityCount?: T;
  headcount?: T;
  iatfCertifiedCount?: T;
  countryCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}